version: '3.8'

services:
  db:
    container_name: findus_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    container_name: findus_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '1121:80'
    depends_on:
      - db
volumes:
  db_data:
